# Generated by Django 3.0.2 on 2020-03-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200320_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostVote',
        ),
    ]
