# Generated by Django 3.0.2 on 2020-03-21 17:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_delete_postvote'),
        ('comments', '0004_delete_commentvote'),
        ('votes', '0002_auto_20200321_1710'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together={('vote', 'user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together={('vote', 'user', 'post')},
        ),
    ]
