GENRES = [
    ('RPG', 'RPG'),
    ('MMO', 'MMO'),
    ('MMORPG', 'MMORPG'),
    ('SHOOTER', 'Shooter'),
    ('J_AND_R', 'Jump & Run'),
    ('OPENW', 'Open-World'),
    ('INDIE', 'Indie'),
    ('STRATEGY', 'Strategy'),
    ('SIMULATION', 'Simulation'),
    ('ADVENTURE', 'Action Adventure'),
    ('METROIDVANIA', 'Metroidvania'),
    ('HORROR', 'Horror'),
    ('SPORT', 'Sport'),
    ('BOARD_GAMES', 'Board Games'),
]