# Generated by Django 3.0.2 on 2020-03-15 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_user.jpg', null=True, upload_to='profile_pics')),
                ('description', models.TextField(default='', max_length=2048)),
                ('genres', multiselectfield.db.fields.MultiSelectField(choices=[('RPG', 'RPG'), ('MMO', 'MMO'), ('MMORPG', 'MMORPG'), ('SHOOTER', 'Shooter'), ('J_AND_R', 'Jump & Run'), ('OPENW', 'Open-World'), ('INDIE', 'Indie'), ('STRATEGY', 'Strategy'), ('SIMULATION', 'Simulation'), ('ADVENTURE', 'Action Adventure'), ('METROIDVANIA', 'Metroidvania'), ('HORROR', 'Horror'), ('SPORT', 'Sport'), ('BOARD_GAMES', 'Board Games')], max_length=110, null=True)),
                ('dark', models.BooleanField(default=True)),
                ('birthdate', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
