# Generated by Django 3.0.2 on 2020-04-28 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(default=[], related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
