# Generated by Django 3.0.2 on 2020-03-15 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=2048, unique=True)),
                ('description', models.TextField(default='', max_length=2048)),
                ('image', models.ImageField(default='default_group.jpg', null=True, upload_to='group_pics')),
                ('genres', multiselectfield.db.fields.MultiSelectField(choices=[('RPG', 'RPG'), ('MMO', 'MMO'), ('MMORPG', 'MMORPG'), ('SHOOTER', 'Shooter'), ('J_AND_R', 'Jump & Run'), ('OPENW', 'Open-World'), ('INDIE', 'Indie'), ('STRATEGY', 'Strategy'), ('SIMULATION', 'Simulation'), ('ADVENTURE', 'Action Adventure'), ('METROIDVANIA', 'Metroidvania'), ('HORROR', 'Horror'), ('SPORT', 'Sport'), ('BOARD_GAMES', 'Board Games')], max_length=110, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_groups', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(default=[], related_name='member_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', '-created_at', 'updated_at', '-updated_at', 'name', '-name', 'owner', '-owner'],
            },
        ),
    ]
